version: 0.1
phases:
  install:
    commands:
      - npm install || (cat /root/.npm/_logs/*-debug.log && false)
  pre_build:
    commands:
      - npm run lint
  build:
    commands:
      - npm run build
  post_build:
    commands:
      # env var BUILD_ARTIFACT_BUCKET is defined in ci
      - aws cloudformation package
         --template-file infrastructure/cf/template.json
         --s3-bucket $BUILD_ARTIFACT_BUCKET
         --output-template-file SamDeploymentTemplate.json
artifacts:
  type: zip
  files:
    - SamDeploymentTemplate.json
